import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/app/components/Header"
import ProviderState from './data/ProviderState'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Final Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <ProviderState>
          <Header />
          {children}
        </ProviderState>
      </body>
    </html>
  )
}
